[2025-06-28 21:55:35.238] [console] [warning] commWarning||Transmission Federate (0)[connecting]::zmq broker connection timed out, trying again (2)
[2025-06-28 21:55:35.239] [console] [warning] commWarning||Transmission Federate (0)[connecting]::sending message to tcp://127.0.0.1:23405
[2025-06-28 21:55:55.285] [console] [error] commERROR||Transmission Federate (0)[connecting]::zmq broker connection timed out after trying 5 times (2)
[2025-06-28 21:55:55.285] [console] [error] commERROR||Transmission Federate (0)[connecting]::receiver connection failure
Traceback (most recent call last):
  File "C:\Users\bulld\Documents\AISustien\Helics_RL\HELICS-Examples\user_guide_examples\misc\gridlabd_example_1\1abc_Transmission_simulator.py", line 41, in <module>
    fed = h.helicsCreateValueFederateFromConfig(f"{case_num}_Transmission_config.json")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bulld\AppData\Roaming\Python\Python312\site-packages\helics\capi.py", line 3669, in helicsCreateValueFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate
